import sqlite3
con = sqlite3.connect("app.db")
con.execute("DROP TABLE IF EXISTS weather;")
con.execute('''CREATE TABLE weather (
    id INTEGER PRIMARY KEY,
    creatat DATETIME,
    changeat DATETIME,
    w_lon DECIMAL(7,4),
    w_lat DECIMAL(7,4),
    s_weather_id INT UNSIGNED,
    s_weather_main VARCHAR(255),
    s_weather_description VARCHAR(255),
    s_weather_icon VARCHAR(255),
    w_base VARCHAR(255),
    s_main_temp DECIMAL(5,2),
    s_main_feels_like DECIMAL(5,2),
    s_main_temp_min DECIMAL(5,2),
    s_main_temp_max DECIMAL(5,2),
    s_main_pressure INT UNSIGNED,
    s_main_humidity INT UNSIGNED,
    s_main_sea_level INT UNSIGNED,
    s_main_grnd_level INT UNSIGNED,
    s_visibility INT UNSIGNED,
    s_wind_speed DECIMAL(5,2),
    s_wind_deg INT UNSIGNED,
    s_wind_gust DECIMAL(5,2),
    s_clouds INT UNSIGNED,
    w_rain_1h DECIMAL(5,2),
    s_rain_3h DECIMAL(5,2),
    w_snow_1h DECIMAL(5,2),
    s_snow_3h DECIMAL(5,2),
    s_dt INT UNSIGNED,
    w_sys_type INT UNSIGNED,
    w_sys_id INT UNSIGNED,
    w_sys_country VARCHAR(255),
    w_sys_sunrise INT UNSIGNED,
    w_sys_sunset INT UNSIGNED,
    w_timezone INT UNSIGNED,
    w_id INT UNSIGNED,
    w_name VARCHAR(255),
    s_cod INT UNSIGNED,
    f_message INT UNSIGNED,
    f_cnt INT UNSIGNED,
    f_temp_kf DECIMAL(5,2),
    f_pop INT UNSIGNED,
    f_sys_pod VARCHAR(255),
    f_dt_txt VARCHAR(255)
);''')
con.commit()
con.close()
